---
matrix:
include:
- language: ruby
  arch:
    - amd64
    - ppc64le
  rvm: 2.6.5
  cache:
    bundler: true
  script:
  - bundle exec rspec
- language: ruby
  arch:
    - amd64
    - ppc64le
  rvm: 2.5.7
  cache:
    bundler: true
  script:
  - bundle exec rspec
- language: go
  go: stable
  arch:
    - amd64
    - ppc64le
  cache:
    directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
  install: true
  script:
  - test -z "$(gofmt -l manageiq-operator)"
  - cd manageiq-operator && go build -o build/_output/bin/manageiq-operator ./cmd/manager
